name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-lambda-package:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: titiler-lambda-python3.13.zip
    permissions:
      contents: write  # Required to upload release assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Lambda package in Docker
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --entrypoint /bin/bash \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            -e PACKAGE_NAME="${{ env.PACKAGE_NAME }}" \
            public.ecr.aws/lambda/python:3.13 \
            build-lambda.sh

      - name: Upload Lambda package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ./${{ env.PACKAGE_NAME }}

      - name: Upload Lambda package to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.PACKAGE_NAME }}
          asset_name: ${{ env.PACKAGE_NAME }}
          asset_content_type: application/zip
